### ISSUE TITLE
Mod-Synth Fails to Response to Mouse

### ISSUE THREAD

**Issue by Capital-EX** [andrevenancio/mod-synth.io#1]
Mod-Synth does not react to any input from Chrome Version 51.0.2704.106 m (64-bit) running on Windows 7. However, the same version of Chrome has no problems with Mod-Synth on Ubuntu 16.04 LTS .

**Comment by andrevenancio** [comment]
is there any error on the console?

**Comment by Capital-EX** [comment]
Nothing appears in the console, even when clicking.

**Comment by andrevenancio** [comment]
Hi @Capital-EX I've just tested this, and works fine. closing this.
