### ISSUE TITLE
No sound in Chrome 67

### ISSUE THREAD

**Issue by daviestar** [andrevenancio/mod-synth.io#2]
```
Uncaught TypeError: 
Failed to execute 'setValueAtTime' on 'AudioParam': 
The provided float value is non-finite.
```

**Comment by andrevenancio** [comment]
Hi @daviestar any other information you can provide regarding this one? I can't reproduce this error.
What browser where you using, what are the steps to reproduce etc.? Thanks

**Comment by daviestar** [comment]
Hey @andrevenancio, it must have been some corrupted state in my browser, I just went back onto the site and got the same error as above, but when I cleared cookies, localstorage and hard refreshed, the sound seems to work fine now 👍 

Sorry, not sure what caused it
